### ISSUE TITLE
Add cypress and jest to github workflows 📦 7

### ISSUE THREAD

**Issue by oyvindrii** [Oyvindeavor/semester-project2#10]
### Create a new file named tests.yml and add the following.

```yml
name: CI Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
lint:
    name: Run Lint-Staged
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run Lint-Staged
      - name: Run Lint-Staged
        run: npx lint-staged

  jest:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run Jest
        run: npm test

  cypress:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Start Development Server
        run: npm run dev &
        env:
          NODE_ENV: development
      - name: Wait for server to start
        run: npx wait-on http://localhost:3000
      - name: Run Cypress
        run: npm run cypress:run

- name: Prettier Check
  run: prettier --check .


```

### Test a pull request to see if its working.
